<a href="https://colab.research.google.com/github/matcgoes/spotify-api-last50songs/blob/main/calc_pilares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [48]:
data = {'TEMPO_FUND': [13,9],
        'SV_12M': [1000, 50000],
        'FL_VCDMERM30_R01_BC': [0, 1],
        'VL_LISEDVTOTMER_01M_BC': [9800, 100000],
        'VL_EDVTOTMER_01M_BC': [20000, 999999],
        'VL_RUREDVTOTMER_01M_BC': [150, 698000],
        'VL_FNMEDVTOTMER_01M_BC': [9856, -999],
        'VL_BNDEDVTOTMER_01M_BC': [1587, np.nan],
        'VL_IMBEDVTOTMER_01M_BC': [0, 1500],
        'VL_VEIEDVTOTMER_01M_BC': [500, 754235],
        'VL_FINIMPEDVTOTMER_01M_BC': [-999, 5000],
        'VL_VCDTOTMER_01M_BCG': [0, 652],
        'VL_PJZTOTMER_01_BCG': [0, -999]      
        }

df = pd.DataFrame(data)

df

,TEMPO_FUND,SV_12M,FL_VCDMERM30_R01_BC,VL_LISEDVTOTMER_01M_BC,VL_EDVTOTMER_01M_BC,VL_RUREDVTOTMER_01M_BC,VL_FNMEDVTOTMER_01M_BC,VL_BNDEDVTOTMER_01M_BC,VL_IMBEDVTOTMER_01M_BC,VL_VEIEDVTOTMER_01M_BC,VL_FINIMPEDVTOTMER_01M_BC,VL_VCDTOTMER_01M_BCG,VL_PJZTOTMER_01_BCG
0,13,1000,0,9800,20000,150,9856,1587.0,0,500,-999,0,0
1,9,50000,1,100000,999999,698000,-999,NaN,1500,754235,5000,652,-999

In [ ]:
vars_nec = ['TEMPO_FUND', 'SV_12M', 'FL_VCDMERM30_R01_BC', 'VL_LISEDVTOTMER_01M_BC',\
            'VL_EDVTOTMER_01M_BC', 'VL_RUREDVTOTMER_01M_BC', 'VL_FNMEDVTOTMER_01M_BC'\
            'VL_BNDEDVTOTMER_01M_BC', 'VL_IMBEDVTOTMER_01M_BC, VL_VEIEDVTOTMER_01M_BC',\
            'VL_FINIMPEDVTOTMER_01M_BC', 'VL_VCDTOTMER_01M_BCG', 'VL_PJZTOTMER_01_BCG']

In [49]:
df

,TEMPO_FUND,SV_12M,FL_VCDMERM30_R01_BC,VL_LISEDVTOTMER_01M_BC,VL_EDVTOTMER_01M_BC,VL_RUREDVTOTMER_01M_BC,VL_FNMEDVTOTMER_01M_BC,VL_BNDEDVTOTMER_01M_BC,VL_IMBEDVTOTMER_01M_BC,VL_VEIEDVTOTMER_01M_BC,VL_FINIMPEDVTOTMER_01M_BC,VL_VCDTOTMER_01M_BCG,VL_PJZTOTMER_01_BCG
0,13,1000,0,9800,20000,150,9856,1587.0,0,500,-999,0,0
1,9,50000,1,100000,999999,698000,-999,NaN,1500,754235,5000,652,-999

In [50]:
#Cria Variavel IND FUND
df['IND_FUND'] = 0
df.loc[df['TEMPO_FUND'] >= 12, 'IND_FUND'] = 1

In [51]:
#Para Cálculo da variavel VL_ALAVANC_01M_BC, vamos tratar as variaveis que fazem parte de sua construção:
#Para isso, se o valor for negativo ou nulo, atribui-se Zero

df.loc[(df['VL_EDVTOTMER_01M_BC'] < 0) | (df['VL_EDVTOTMER_01M_BC'].isnull()), 'VL_EDVTOTMER_01M_BC'] = 0
df.loc[(df['VL_RUREDVTOTMER_01M_BC'] < 0) | (df['VL_RUREDVTOTMER_01M_BC'].isnull()), 'VL_RUREDVTOTMER_01M_BC'] = 0
df.loc[(df['VL_FNMEDVTOTMER_01M_BC'] < 0) | (df['VL_FNMEDVTOTMER_01M_BC'].isnull()), 'VL_FNMEDVTOTMER_01M_BC'] = 0
df.loc[(df['VL_BNDEDVTOTMER_01M_BC'] < 0) | (df['VL_BNDEDVTOTMER_01M_BC'].isnull()), 'VL_BNDEDVTOTMER_01M_BC'] = 0
df.loc[(df['VL_IMBEDVTOTMER_01M_BC'] < 0) | (df['VL_IMBEDVTOTMER_01M_BC'].isnull()), 'VL_IMBEDVTOTMER_01M_BC'] = 0
df.loc[(df['VL_VEIEDVTOTMER_01M_BC'] < 0) | (df['VL_VEIEDVTOTMER_01M_BC'].isnull()), 'VL_VEIEDVTOTMER_01M_BC'] = 0
df.loc[(df['VL_FINIMPEDVTOTMER_01M_BC'] < 0) | (df['VL_FINIMPEDVTOTMER_01M_BC'].isnull()), 'VL_FINIMPEDVTOTMER_01M_BC'] = 0

df['VL_ALAVANC_01M_BC'] = df['VL_EDVTOTMER_01M_BC'] - \
                          df['VL_RUREDVTOTMER_01M_BC'] - \
                          df['VL_FNMEDVTOTMER_01M_BC'] - \
                          df['VL_BNDEDVTOTMER_01M_BC'] - \
                          df['VL_IMBEDVTOTMER_01M_BC'] - \
                          df['VL_VEIEDVTOTMER_01M_BC'] - \
                          df['VL_FINIMPEDVTOTMER_01M_BC']

In [52]:
df['SV_ALAVANC_MIC'] = df['SV_12M']
df['SV_ALAVANC_PQN'] = df['SV_12M']
df['SV_ALAVANC_MED'] = df['SV_12M']
df['SV_ALAVANC_GDE'] = df['SV_12M']

#Atribui Piso de Sinal Vital
df.loc[(df['SV_12M'] < 3000) | (df['SV_12M'].isnull()), 'SV_ALAVANC_MIC'] = 3000
df.loc[(df['SV_12M'] < 100000) | (df['SV_12M'].isnull()), 'SV_ALAVANC_PQN'] = 100000
df.loc[(df['SV_12M'] < 500000) | (df['SV_12M'].isnull()), 'SV_ALAVANC_MED'] = 500000
df.loc[(df['SV_12M'] < 1000000) | (df['SV_12M'].isnull()), 'SV_ALAVANC_GDE'] = 1000000

In [18]:
df

,TEMPO_FUND,SV_12M,FL_VCDMERM30_R01_BC,VL_LISEDVTOTMER_01M_BC,VL_EDVTOTMER_01M_BC,VL_RUREDVTOTMER_01M_BC,VL_FNMEDVTOTMER_01M_BC,VL_BNDEDVTOTMER_01M_BC,VL_IMBEDVTOTMER_01M_BC,VL_VEIEDVTOTMER_01M_BC,VL_FINIMPEDVTOTMER_01M_BC,VL_VCDTOTMER_01M_BCG,VL_PJZTOTMER_01_BCG,IND_FUND,VL_ALAVANC_01M_BC,SV_ALAVANC_MIC,SV_ALAVANC_PQN,SV_ALAVANC_MED,SV_ALAVANC_GDE
0,13,1000,0,9800,20000,150,9856,1587.0,0,500,0,0,0,1,7907.0,3000,100000,500000,1000000
1,9,50000,1,100000,999999,698000,0,0.0,1500,754235,5000,652,-999,0,-458736.0,50000,100000,500000,1000000

In [53]:
df['VL_ALAV_SV_01M_BC_MIC'] = df['VL_ALAVANC_01M_BC']/df['SV_ALAVANC_MIC']
df['VL_ALAV_SV_01M_BC_PQN'] = df['VL_ALAVANC_01M_BC']/df['SV_ALAVANC_PQN']
df['VL_ALAV_SV_01M_BC_MED'] = df['VL_ALAVANC_01M_BC']/df['SV_ALAVANC_MED']
df['VL_ALAV_SV_01M_BC_GDE'] = df['VL_ALAVANC_01M_BC']/df['SV_ALAVANC_GDE']

In [58]:
def pilar_ala_ind_mic(df):
  if df['VL_ALAVANC_01M_BC'] < 150 and df['IND_FUND'] == 1:
    return '2'
  elif df['VL_ALAVANC_01M_BC'] < 150 and df['IND_FUND'] == 0:
    return '3'
  elif df['VL_ALAV_SV_01M_BC_MIC'] < 0.01 and df['IND_FUND'] == 1:
   return '1'
  elif df['VL_ALAV_SV_01M_BC_MIC'] < 0.03 and df['IND_FUND'] == 1: 
    return '2'
  elif df['VL_ALAV_SV_01M_BC_MIC'] < 0.10 and df['IND_FUND'] == 1:
    return '3'
  elif df['IND_FUND'] == 1:
    return '4'
  elif df['VL_ALAV_SV_01M_BC_MIC'] < 0.01 and df['IND_FUND'] == 0:
    return '2' 
  elif df['VL_ALAV_SV_01M_BC_MIC'] < 0.05 and df['IND_FUND'] == 0:
    return '4'
  elif df['IND_FUND'] == 0:
    return '5'

def pilar_ala_ind_pqn(df):
  if df['VL_ALAVANC_01M_BC'] < 250 and df['IND_FUND'] == 1:
    return '1'
  elif df['VL_ALAVANC_01M_BC'] < 250 and df['IND_FUND'] == 0:
    return '1'
  elif df['VL_ALAV_SV_01M_BC_PQN'] < 0.01:
    return '1'
  elif df['VL_ALAV_SV_01M_BC_PQN'] < 0.02: 
    return '2'
  elif df['VL_ALAV_SV_01M_BC_PQN'] < 0.50:
    return '3'
  else:
    return '4'

def pilar_ala_ind_med(df):
  if df['VL_ALAVANC_01M_BC'] < 250 and df['IND_FUND'] == 1:
    return '1'
  elif df['VL_ALAVANC_01M_BC'] < 250 and df['IND_FUND'] == 0:
    return '1'
  elif df['VL_ALAV_SV_01M_BC_MED'] < 0.01:
    return '1'
  elif df['VL_ALAV_SV_01M_BC_MED'] < 0.20: 
    return '2'
  else:
    return '3'

def pilar_ala_ind_gde(df):
  if df['VL_ALAVANC_01M_BC'] < 250 and df['IND_FUND'] == 1:
    return '1'
  elif df['VL_ALAVANC_01M_BC'] < 250 and df['IND_FUND'] == 0:
    return '1'
  elif df['VL_ALAV_SV_01M_BC_GDE'] < 0.01:
    return '1'
  elif df['VL_ALAV_SV_01M_BC_GDE'] < 0.20: 
    return '2'
  else:
    return '3'

In [59]:
df['PILAR_JORNR_ALA_IND_MIC'] = df.apply(pilar_ala_ind_mic, axis = 1)
df['PILAR_JORNR_ALA_IND_PQN'] = df.apply(pilar_ala_ind_pqn, axis = 1)
df['PILAR_JORNR_ALA_IND_MED'] = df.apply(pilar_ala_ind_med, axis = 1)
df['PILAR_JORNR_ALA_IND_GDE'] = df.apply(pilar_ala_ind_gde, axis = 1)

In [60]:
df

,TEMPO_FUND,SV_12M,FL_VCDMERM30_R01_BC,VL_LISEDVTOTMER_01M_BC,VL_EDVTOTMER_01M_BC,VL_RUREDVTOTMER_01M_BC,VL_FNMEDVTOTMER_01M_BC,VL_BNDEDVTOTMER_01M_BC,VL_IMBEDVTOTMER_01M_BC,VL_VEIEDVTOTMER_01M_BC,VL_FINIMPEDVTOTMER_01M_BC,VL_VCDTOTMER_01M_BCG,VL_PJZTOTMER_01_BCG,IND_FUND,VL_ALAVANC_01M_BC,SV_ALAVANC_MIC,SV_ALAVANC_PQN,SV_ALAVANC_MED,SV_ALAVANC_GDE,VL_ALAV_SV_01M_BC_MIC,VL_ALAV_SV_01M_BC_PQN,VL_ALAV_SV_01M_BC_MED,VL_ALAV_SV_01M_BC_GDE,PILAR_JORNR_ALA_IND_MIC,PILAR_JORNR_ALA_IND_PQN,PILAR_JORNR_ALA_IND_MED,PILAR_JORNR_ALA_IND_GDE
0,13,1000,0,9800,20000,150,9856,1587.0,0,500,0,0,0,1,7907.0,3000,100000,500000,1000000,2.635667,0.07907,0.015814,0.007907,4,3,2,1
1,9,50000,1,100000,999999,698000,0,0.0,1500,754235,5000,652,-999,0,-458736.0,50000,100000,500000,1000000,-9.174720,-4.58736,-0.917472,-0.458736,3,1,1,1

In [61]:
#Micro
df['T_MIC_VL_LISEDV_SV_01M_BC'] = df['VL_LISEDVTOTMER_01M_BC']/df['SV_ALAVANC_MIC']

df.loc[df['VL_LISEDVTOTMER_01M_BC'].isnull(), 'T_MIC_VL_LISEDV_SV_01M_BC'] = np.nan
df.loc[df['VL_LISEDVTOTMER_01M_BC'] == -99, 'T_MIC_VL_LISEDV_SV_01M_BC'] = -99
df.loc[df['VL_LISEDVTOTMER_01M_BC'] < 250, 'T_MIC_VL_LISEDV_SV_01M_BC'] = -999
df.loc[df['SV_12M'].isnull(), 'T_MIC_VL_LISEDV_SV_01M_BC'] = -9999
df.loc[df['SV_12M'] == -999, 'T_MIC_VL_LISEDV_SV_01M_BC'] = -99999
df.loc[df['SV_12M'] < 250, 'T_MIC_VL_LISEDV_SV_01M_BC'] = -999999

#Pequena
df['T_PQN_VL_LISEDV_SV_01M_BC'] = df['VL_LISEDVTOTMER_01M_BC']/df['SV_ALAVANC_PQN']

df.loc[df['VL_LISEDVTOTMER_01M_BC'].isnull(), 'T_PQN_VL_LISEDV_SV_01M_BC'] = np.nan
df.loc[df['VL_LISEDVTOTMER_01M_BC'] == -99, 'T_PQN_VL_LISEDV_SV_01M_BC'] = -99
df.loc[df['VL_LISEDVTOTMER_01M_BC'] < 250, 'T_PQN_VL_LISEDV_SV_01M_BC'] = -999
df.loc[df['SV_12M'].isnull(), 'T_PQN_VL_LISEDV_SV_01M_BC'] = -9999
df.loc[df['SV_12M'] == -999, 'T_PQN_VL_LISEDV_SV_01M_BC'] = -99999
df.loc[df['SV_12M'] < 250, 'T_PQN_VL_LISEDV_SV_01M_BC'] = -999999

#Media
df['T_MED_VL_LISEDV_SV_01M_BC'] = df['VL_LISEDVTOTMER_01M_BC']/df['SV_ALAVANC_MED']

df.loc[df['VL_LISEDVTOTMER_01M_BC'].isnull(), 'T_MED_VL_LISEDV_SV_01M_BC'] = np.nan
df.loc[df['VL_LISEDVTOTMER_01M_BC'] == -99, 'T_MED_VL_LISEDV_SV_01M_BC'] = -99
df.loc[df['VL_LISEDVTOTMER_01M_BC'] < 250, 'T_MED_VL_LISEDV_SV_01M_BC'] = -999
df.loc[df['SV_12M'].isnull(), 'T_MED_VL_LISEDV_SV_01M_BC'] = -9999
df.loc[df['SV_12M'] == -999, 'T_MED_VL_LISEDV_SV_01M_BC'] = -99999
df.loc[df['SV_12M'] < 250, 'T_MED_VL_LISEDV_SV_01M_BC'] = -999999

#Grande
df['T_GDE_VL_LISEDV_SV_01M_BC'] = df['VL_LISEDVTOTMER_01M_BC']/df['SV_ALAVANC_GDE']

df.loc[df['VL_LISEDVTOTMER_01M_BC'].isnull(), 'T_GDE_VL_LISEDV_SV_01M_BC'] = np.nan
df.loc[df['VL_LISEDVTOTMER_01M_BC'] == -99, 'T_GDE_VL_LISEDV_SV_01M_BC'] = -99
df.loc[df['VL_LISEDVTOTMER_01M_BC'] < 250, 'T_GDE_VL_LISEDV_SV_01M_BC'] = -999
df.loc[df['SV_12M'].isnull(), 'T_GDE_VL_LISEDV_SV_01M_BC'] = -9999
df.loc[df['SV_12M'] == -999, 'T_GDE_VL_LISEDV_SV_01M_BC'] = -99999
df.loc[df['SV_12M'] < 250, 'T_GDE_VL_LISEDV_SV_01M_BC'] = -999999

In [63]:
#Micro
df['T_MIC_VL_VCDTOT_SV_01M_BCG'] = df['VL_VCDTOTMER_01M_BCG']/df['SV_ALAVANC_MIC']

df.loc[df['VL_VCDTOTMER_01M_BCG'].isnull(), 'T_MIC_VL_VCDTOT_SV_01M_BCG'] = np.nan
df.loc[df['VL_VCDTOTMER_01M_BCG'] == -99, 'T_MIC_VL_VCDTOT_SV_01M_BCG'] = -99
df.loc[df['VL_VCDTOTMER_01M_BCG'] < 250, 'T_MIC_VL_VCDTOT_SV_01M_BCG'] = -999
df.loc[df['SV_12M'].isnull(), 'T_MIC_VL_VCDTOT_SV_01M_BCG'] = -9999
df.loc[df['SV_12M'] == -999, 'T_MIC_VL_VCDTOT_SV_01M_BCG'] = -99999
df.loc[df['SV_12M'] < 250, 'T_MIC_VL_VCDTOT_SV_01M_BCG'] = -999999

#Pequena
df['T_PQN_VL_VCDTOT_SV_01M_BCG'] = df['VL_VCDTOTMER_01M_BCG']/df['SV_ALAVANC_PQN']

df.loc[df['VL_VCDTOTMER_01M_BCG'].isnull(), 'T_PQN_VL_VCDTOT_SV_01M_BCG'] = np.nan
df.loc[df['VL_VCDTOTMER_01M_BCG'] == -99, 'T_PQN_VL_VCDTOT_SV_01M_BCG'] = -99
df.loc[df['VL_VCDTOTMER_01M_BCG'] < 250, 'T_PQN_VL_VCDTOT_SV_01M_BCG'] = -999
df.loc[df['SV_12M'].isnull(), 'T_PQN_VL_VCDTOT_SV_01M_BCG'] = -9999
df.loc[df['SV_12M'] == -999, 'T_PQN_VL_VCDTOT_SV_01M_BCG'] = -99999
df.loc[df['SV_12M'] < 250, 'T_PQN_VL_VCDTOT_SV_01M_BCG'] = -999999

#Media
df['T_MED_VL_VCDTOT_SV_01M_BCG'] = df['VL_VCDTOTMER_01M_BCG']/df['SV_ALAVANC_MED']

df.loc[df['VL_VCDTOTMER_01M_BCG'].isnull(), 'T_MED_VL_VCDTOT_SV_01M_BCG'] = np.nan
df.loc[df['VL_VCDTOTMER_01M_BCG'] == -99, 'T_MED_VL_VCDTOT_SV_01M_BCG'] = -99
df.loc[df['VL_VCDTOTMER_01M_BCG'] < 250, 'T_MED_VL_VCDTOT_SV_01M_BCG'] = -999
df.loc[df['SV_12M'].isnull(), 'T_MED_VL_VCDTOT_SV_01M_BCG'] = -9999
df.loc[df['SV_12M'] == -999, 'T_MED_VL_VCDTOT_SV_01M_BCG'] = -99999
df.loc[df['SV_12M'] < 250, 'T_MED_VL_VCDTOT_SV_01M_BCG'] = -999999

#Grande
df['T_GDE_VL_VCDTOT_SV_01M_BCG'] = df['VL_VCDTOTMER_01M_BCG']/df['SV_ALAVANC_GDE']

df.loc[df['VL_VCDTOTMER_01M_BCG'].isnull(), 'T_GDE_VL_VCDTOT_SV_01M_BCG'] = np.nan
df.loc[df['VL_VCDTOTMER_01M_BCG'] == -99, 'T_GDE_VL_VCDTOT_SV_01M_BCG'] = -99
df.loc[df['VL_VCDTOTMER_01M_BCG'] < 250, 'T_GDE_VL_VCDTOT_SV_01M_BCG'] = -999
df.loc[df['SV_12M'].isnull(), 'T_GDE_VL_VCDTOT_SV_01M_BCG'] = -9999
df.loc[df['SV_12M'] == -999, 'T_GDE_VL_VCDTOT_SV_01M_BCG'] = -99999
df.loc[df['SV_12M'] < 250, 'T_GDE_VL_VCDTOT_SV_01M_BCG'] = -999999

In [64]:
df

,TEMPO_FUND,SV_12M,FL_VCDMERM30_R01_BC,VL_LISEDVTOTMER_01M_BC,VL_EDVTOTMER_01M_BC,VL_RUREDVTOTMER_01M_BC,VL_FNMEDVTOTMER_01M_BC,VL_BNDEDVTOTMER_01M_BC,VL_IMBEDVTOTMER_01M_BC,VL_VEIEDVTOTMER_01M_BC,VL_FINIMPEDVTOTMER_01M_BC,VL_VCDTOTMER_01M_BCG,VL_PJZTOTMER_01_BCG,IND_FUND,VL_ALAVANC_01M_BC,SV_ALAVANC_MIC,SV_ALAVANC_PQN,SV_ALAVANC_MED,SV_ALAVANC_GDE,VL_ALAV_SV_01M_BC_MIC,VL_ALAV_SV_01M_BC_PQN,VL_ALAV_SV_01M_BC_MED,VL_ALAV_SV_01M_BC_GDE,PILAR_JORNR_ALA_IND_MIC,PILAR_JORNR_ALA_IND_PQN,PILAR_JORNR_ALA_IND_MED,PILAR_JORNR_ALA_IND_GDE,T_MIC_VL_LISEDV_SV_01M_BC,T_MIC_VL_VCDTOT_SV_01M_BCG,T_PQN_VL_VCDTOT_SV_01M_BCG,T_MED_VL_VCDTOT_SV_01M_BCG,T_GDE_VL_VCDTOT_SV_01M_BCG
0,13,1000,0,9800,20000,150,9856,1587.0,0,500,0,0,0,1,7907.0,3000,100000,500000,1000000,2.635667,0.07907,0.015814,0.007907,4,3,2,1,3.266667,-999.00000,-999.00000,-999.000000,-999.000000
1,9,50000,1,100000,999999,698000,0,0.0,1500,754235,5000,652,-999,0,-458736.0,50000,100000,500000,1000000,-9.174720,-4.58736,-0.917472,-0.458736,3,1,1,1,2.000000,0.01304,0.00652,0.001304,0.000652

In [57]:
df['PILAR_JORNR_ALA_IND_MIC'] = '5' #Pior categoria
print(df['PILAR_JORNR_ALA_IND_MIC'])

df.loc[(df['VL_ALAV_SV_01M_BC_MIC'] < 0.01) & (df['IND_FUND'] == 1),'PILAR_JORNR_ALA_IND_MIC'] = '1'
print(df['PILAR_JORNR_ALA_IND_MIC'])

df.loc[((df['IND_FUND'] == 1) & ((df['VL_ALAVANC_01M_BC'] < 150) | (df['VL_ALAV_SV_01M_BC_MIC'] < 0.03))) | ((df['VL_ALAV_SV_01M_BC_MIC'] < 0.01) & (df['IND_FUND'] == 0)), 'PILAR_JORNR_ALA_IND_MIC'] = '2'
print(df['PILAR_JORNR_ALA_IND_MIC'])

df.loc[((df['VL_ALAVANC_01M_BC'] < 150) & (df['IND_FUND'] == 0)) | ((df['VL_ALAV_SV_01M_BC_MIC'] < 0.10) & (df['IND_FUND'] == 1)), 'PILAR_JORNR_ALA_IND_MIC'] = '3'
print(df['PILAR_JORNR_ALA_IND_MIC'])

df.loc[(df['IND_FUND'] == 1) | ((df['VL_ALAV_SV_01M_BC_MIC'] < 0.05) & (df['IND_FUND'] == 0)), 'PILAR_JORNR_ALA_IND_MIC'] = '4'
print(df['PILAR_JORNR_ALA_IND_MIC'])

# df.loc[((df['VL_ALAVANC_01M_BC'] < 150) & (df['IND_FUND'] == 1)) | (df['VL_ALAV_SV_01M_BC_MIC'] < 0.03) & (df['IND_FUND'] == 1),'PILAR_JORNR_ALA_IND_MIC'] = '2'

0    5
1    5
Name: PILAR_JORNR_ALA_IND_MIC, dtype: object
0    5
1    5
Name: PILAR_JORNR_ALA_IND_MIC, dtype: object
0    5
1    2
Name: PILAR_JORNR_ALA_IND_MIC, dtype: object
0    5
1    3
Name: PILAR_JORNR_ALA_IND_MIC, dtype: object
0    4
1    4
Name: PILAR_JORNR_ALA_IND_MIC, dtype: object

In [46]:
df

,TEMPO_FUND,SV_12M,FL_VCDMERM30_R01_BC,VL_LISEDVTOTMER_01M_BC,VL_EDVTOTMER_01M_BC,VL_RUREDVTOTMER_01M_BC,VL_FNMEDVTOTMER_01M_BC,VL_BNDEDVTOTMER_01M_BC,VL_IMBEDVTOTMER_01M_BC,VL_VEIEDVTOTMER_01M_BC,VL_FINIMPEDVTOTMER_01M_BC,VL_VCDTOTMER_01M_BCG,VL_PJZTOTMER_01_BCG,IND_FUND,VL_ALAVANC_01M_BC,SV_ALAVANC_MIC,SV_ALAVANC_PQN,SV_ALAVANC_MED,SV_ALAVANC_GDE,VL_ALAV_SV_01M_BC_MIC,VL_ALAV_SV_01M_BC_PQN,VL_ALAV_SV_01M_BC_MED,VL_ALAV_SV_01M_BC_GDE,PILAR_JORNR_ALA_IND_MIC
0,13,1000,0,9800,20000,150,9856,1587.0,0,500,0,0,0,1,7907.0,3000,100000,500000,1000000,2.635667,0.07907,0.015814,0.007907,4
1,9,50000,1,100000,999999,698000,0,0.0,1500,754235,5000,652,-999,0,-458736.0,50000,100000,500000,1000000,-9.174720,-4.58736,-0.917472,-0.458736,4

In [35]:
df['PILAR_JORNR_ALA_IND_PQN'] = '4' #Pior categoria
print(df['PILAR_JORNR_ALA_IND_PQN'])

df.loc[((df['VL_ALAVANC_01M_BC'] < 250) & (df['IND_FUND'] == 1)) | ((df['VL_ALAVANC_01M_BC'] < 250) & (df['IND_FUND'] == 0)) | (df['VL_ALAV_SV_01M_BC_PQN'] < 0.01) , 'PILAR_JORNR_ALA_IND_PQN'] = '1'
print(df['PILAR_JORNR_ALA_IND_PQN'])
df.loc[df['VL_ALAV_SV_01M_BC_PQN'] < 0.02, 'PILAR_JORNR_ALA_IND_PQN'] = '2'
print(df['PILAR_JORNR_ALA_IND_PQN'])
df.loc[df['VL_ALAV_SV_01M_BC_PQN'] < 0.50, 'PILAR_JORNR_ALA_IND_PQN'] = '3'
print(df['PILAR_JORNR_ALA_IND_PQN'])

0    4
1    4
Name: PILAR_JORNR_ALA_IND_PQN, dtype: object
0    4
1    1
Name: PILAR_JORNR_ALA_IND_PQN, dtype: object
0    4
1    2
Name: PILAR_JORNR_ALA_IND_PQN, dtype: object
0    3
1    3
Name: PILAR_JORNR_ALA_IND_PQN, dtype: object

In [34]:
print(df['PILAR_JORNR_ALA_IND_PQN'])

0    3
1    3
Name: PILAR_JORNR_ALA_IND_PQN, dtype: object